<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payslip</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
            color: #4849E8;
        }
        .payslip-title {
            font-size: 18px;
            margin-top: 10px;
        }
        .info-section {
            margin: 20px 0;
        }
        .info-row {
            display: flex;
            justify-content: space-between;
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #4849E8;
            color: white;
        }
        .total-row {
            font-weight: bold;
            background-color: #f5f5f5;
        }
        .net-pay {
            font-size: 16px;
            font-weight: bold;
            color: #4849E8;
            text-align: right;
            margin-top: 20px;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-name">SmartHR</div>
        <div class="payslip-title">Employee Payslip</div>
        <div>Period: {{ $startDate->format('F Y') }}</div>
    </div>

    <div class="info-section">
        <div class="info-row">
            <div><strong>Employee ID:</strong> {{ $employee->employeeID }}</div>
            <div><strong>Date Generated:</strong> {{ now()->format('M d, Y') }}</div>
        </div>
        <div class="info-row">
            <div><strong>Name:</strong> {{ $employee->firstName }} {{ $employee->lastName }}</div>
            <div><strong>Department:</strong> {{ $employee->department->departmentName ?? $employee->departmentID }}</div>
        </div>
        <div class="info-row">
            <div><strong>Position:</strong> {{ $employee->position }}</div>
            <div><strong>Period:</strong> {{ $startDate->format('M d') }} - {{ $endDate->format('M d, Y') }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th style="text-align: right;">Amount (₱)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Base Salary</td>
                <td style="text-align: right;">{{ number_format($regularPay, 2) }}</td>
            </tr>
            <tr>
                <td>Overtime Pay ({{ number_format($overtimeHours, 2) }} hrs @ ₱{{ number_format($employee->rate * 1.5, 2) }}/hr)</td>
                <td style="text-align: right;">{{ number_format($overtimePay, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td>Gross Pay</td>
                <td style="text-align: right;">{{ number_format($grossPay, 2) }}</td>
            </tr>
            <tr>
                <td colspan="2"><strong>Deductions</strong></td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;SSS (4.5%)</td>
                <td style="text-align: right;">- {{ number_format($sss, 2) }}</td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;PhilHealth (2%)</td>
                <td style="text-align: right;">- {{ number_format($philHealth, 2) }}</td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;Pag-IBIG</td>
                <td style="text-align: right;">- {{ number_format($pagibig, 2) }}</td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;Withholding Tax (15%)</td>
                <td style="text-align: right;">- {{ number_format($tax, 2) }}</td>
            </tr>
            <tr class="total-row">
                <td>Total Deductions</td>
                <td style="text-align: right;">{{ number_format($totalDeductions, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="net-pay">
        NET PAY: ₱{{ number_format($netPay, 2) }}
    </div>

    <div class="footer">
        <p>This is a computer-generated payslip. No signature required.</p>
        <p>Generated by SmartHR System on {{ now()->format('M d, Y h:i A') }}</p>
    </div>
</body>
</html>
